In [1]:
import bittensor
import torch 
from transformers import AutoTokenizer
import numpy as np

In [3]:
logging=bittensor.logging()
dataload = bittensor.dataloader(max_corpus_size=10000)


2021-09-13 10:55:03.943 |     SUCCESS      | Set debug:          OFF
2021-09-13 10:55:03.945 |     SUCCESS      | Set trace:          OFF
2021-09-13 10:55:03.945 |     SUCCESS      | Set record log:     OFF


In [4]:
tokenizer = AutoTokenizer.from_pretrained("gpt2")


NameError: name 'data' is not defined

In [4]:
test = next(data_iter)
print(test)

tensor([[ 4480,    45, 12305,    64,  4703,   270,  1169, 16354, 22540,   265,
            45, 12305,  3791, 49278, 14941, 31810,   261, 16157,  2078,    11],
        [   45, 12305,    64,  4703,   270,  1169, 16354, 22540,   265,    45,
         12305,  3791, 49278, 14941, 31810,   261, 16157,  2078,    11, 35411],
        [42122,    64,  4703,   270,  1169, 16354, 22540,   265,    45, 12305,
          3791, 49278, 14941, 31810,   261, 16157,  2078,    11, 35411,    13],
        [   64,  4703,   270,  1169, 16354, 22540,   265,    45, 12305,  3791,
         49278, 14941, 31810,   261, 16157,  2078,    11, 35411,    13, 15017],
        [ 4703,   270,  1169, 16354, 22540,   265,    45, 12305,  3791, 49278,
         14941, 31810,   261, 16157,  2078,    11, 35411,    13, 15017,  3841],
        [ 1462,  1169, 16354, 22540,   265,    45, 12305,  3791, 49278, 14941,
         31810,   261, 16157,  2078,    11, 35411,    13, 15017,  3841,  1462],
        [ 1169, 16354, 22540,   265,    45, 12

In [4]:
for epoch in np.arange(100):
    print('New Epoch',epoch)
    data = dataload.dataloader(epoch_length=100)
    data_iter = iter(data)
    test = next(data_iter)
    print(test[0])
    decoded = [bittensor.tokenizer().decode(i) for i in test[0]]
    print(decoded)
    test = next(data_iter)
    print(test[0])
    decoded = [bittensor.tokenizer().decode(i) for i in test[0]]
    print(decoded)
    #hugging = tokenizer(decoded)
    #print(len(hugging['input_ids']))
    #print(model(test[j]))


New Epoch 0
2021-09-13 10:55:13.823 |     SUCCESS      | Retrieving a dataset files from the IPFS gateway...
2021-09-13 10:55:14.309 |     SUCCESS      | Loaded folder:      QmXwfPoh2QFYqC6cYcW8kzyd9ruFfhnUi2kVBkdhawjUzj
2021-09-13 10:55:15.269 |     SUCCESS      | Loaded folder:      QmRjFNn3XpYMycVzTE4YcVcxk45vNZcTAjKmtEqPLKwAWd
2021-09-13 10:55:15.785 |     SUCCESS      | Downloaded:         Wikitext_KirShara.txt
2021-09-13 10:55:15.786 |     SUCCESS      | Saved:              Wikitext_KirShara.txt
tensor([ 4758, 43439,  1169, 14986,    53,   377,  5171,  1462,  1169,  3041,
         1161, 15898,  6738,     1,   464, 19857,     1,   261,  2017,  4853])
['which', 'saw', 'the', 'original', 'V', 'ul', 'can', 'to', 'the', 'Re', 'formation', 'seen', 'from', '"', 'The', 'Forge', '"', 'on', 'wards', 'equ']
tensor([   75, 10533, 43764,    51,     6,  8017, 13552,    11,    51,     6,
        35882,  9908,  7697,     8,    13, 13887, 10755,     1, 23155, 18800])
['l', 'ocated', 'killing', 'T

2021-09-13 10:55:25.997 |     SUCCESS      | Loaded folder:      QmXwfPoh2QFYqC6cYcW8kzyd9ruFfhnUi2kVBkdhawjUzj
2021-09-13 10:55:28.521 |     SUCCESS      | Loaded folder:      QmRjFNn3XpYMycVzTE4YcVcxk45vNZcTAjKmtEqPLKwAWd
2021-09-13 10:55:28.927 |     SUCCESS      | Downloaded:         Wikitext_BattleofPellsPoint.txt
2021-09-13 10:55:28.928 |     SUCCESS      | Saved:              Wikitext_BattleofPellsPoint.txt
tensor([ 8199,   694,   817,  3828,    82, 11612,  3289,   292,   817, 10823,
        30171,   261, 14508,  4002,   292,   817, 10823,    11,    37,  3828])
['Ne', 'ck', 'Th', 'rog', 's', 'orig', 'inally', 'as', 'Th', 'rock', 'mort', 'on', 'also', 'known', 'as', 'Th', 'rock', ',', 'F', 'rog']
tensor([  261,  1169,   271,  1044,  5124, 12904,   464, 17636,   400,    86,
        19112,    11,   392, 13746,    13, 17121,  2437,    68,  9503,  4066])
['on', 'the', 'is', 'land', 'Man', 'hattan', 'The', 'Americans', 'th', 'w', 'arted', ',', 'and', 'Gen', '.', 'William', 'How', 'e',

2021-09-13 10:55:41.122 |     SUCCESS      | Loaded folder:      QmXwfPoh2QFYqC6cYcW8kzyd9ruFfhnUi2kVBkdhawjUzj
2021-09-13 10:55:44.153 |     SUCCESS      | Loaded folder:      QmRjFNn3XpYMycVzTE4YcVcxk45vNZcTAjKmtEqPLKwAWd
2021-09-13 10:55:44.759 |     SUCCESS      | Downloaded:         Wikitext_WhiteDog.txt
2021-09-13 10:55:44.760 |     SUCCESS      | Saved:              Wikitext_WhiteDog.txt
tensor([ 1169, 26240,   271,  8612,   453,   292,    64,    33,    12, 41364,
           11,   270,  9776, 15003,  1927,  1525, 22213,   873,   896, 20979])
['the', 'film', 'is', 'gener', 'ally', 'as', 'a', 'B', '-', 'movie', ',', 'it', 'was', 'init', 'ially', 'by', 'crit', 'ics', 'its', 'release']
tensor([ 4758, 20274,   276,    79, 40225, 22213,   873, 31629, 11377,  9446,
           13,   464, 26240,  9776,    69,  3289,   403, 30147,  4480, 10044])
['which', 'result', 'ed', 'p', 'raise', 'crit', 'ics', 'little', 'public', 'interest', '.', 'The', 'film', 'was', 'f', 'inally', 'un', 'released'

tensor([ 4869,     4,  1659, 12114,  8107,   259,    36,    83,   418,  3099,
        14150, 42552,   276,  5661, 36151,  1525,    69, 37971,    75,   507])
['71', '%', 'of', 'hy', 'ena', 'in', 'E', 't', 'os', 'ha', 'have', 'adapt', 'ed', 'this', 'pressure', 'by', 'f', 'requently', 'l', 'ions']
New Epoch 35
tensor([   11,  1169,  2777,  8426,  2411,   444,   261, 18627, 14813,  5796,
          695, 20088,   889,   392, 22437,  1662, 27780,   896,  3866,    88])
[',', 'the', 'sp', 'otted', 'rel', 'ies', 'on', 'sight', 'than', 'sm', 'ell', 'hun', 'ting', 'and', 'does', 'not', 'follow', 'its', 'pre', 'y']
tensor([   11,   392, 11261, 20657,   732,  2573,   258,   282,    34, 23161,
         6286,  4480,  4215,    11, 33282,   680, 27108,    11,   392,   732])
[',', 'and', 'may', 'take', 'we', 'eks', 'he', 'al', 'C', 'ubs', 'born', 'with', 'soft', ',', 'brown', 'ish', 'hair', ',', 'and', 'we']
New Epoch 36
tensor([ 1169, 11227,   874,  9423,   462,  3653,   558,   464, 40226, 14922,
      

2021-09-13 10:56:23.931 |     SUCCESS      | Loaded folder:      QmXwfPoh2QFYqC6cYcW8kzyd9ruFfhnUi2kVBkdhawjUzj
2021-09-13 10:56:28.485 |     SUCCESS      | Loaded folder:      QmRjFNn3XpYMycVzTE4YcVcxk45vNZcTAjKmtEqPLKwAWd
2021-09-13 10:56:28.491 |     SUCCESS      | Loaded:             Wikitext_FlyontheWallsong.txt
tensor([  265, 17618,  1954, 19052,  7207,   278,  1169, 40926,   261, 16192,
         1065,    13,   818, 15160,  7496,  1169, 34050, 11275,  7241,   431])
['at', 'number', '23', 'before', 'fall', 'ing', 'the', 'chart', 'on', 'March', '12', '.', 'In', 'Aust', 'ria', 'the', 'song', 'deb', 'uted', 'pe']
tensor([ 1640,  1169, 10464,  1571, 16784,    19,    13,   818,  1169, 22030,
        21352,  3064,    11,     1, 33771,   261,  1169, 22401,     1,   431])
['for', 'the', 'week', 'ending', 'April', '4', '.', 'In', 'the', 'European', 'Hot', '100', ',', '"', 'Fly', 'on', 'the', 'Wall', '"', 'pe']
New Epoch 46
2021-09-13 10:56:28.524 |     SUCCESS      | Retrieving a dataset f

2021-09-13 10:56:43.328 |     SUCCESS      | Loaded folder:      QmRjFNn3XpYMycVzTE4YcVcxk45vNZcTAjKmtEqPLKwAWd
2021-09-13 10:56:43.932 |     SUCCESS      | Downloaded:         Wikitext_TheLastTemptationofHomer.txt
2021-09-13 10:56:43.932 |     SUCCESS      | Saved:              Wikitext_TheLastTemptationofHomer.txt
tensor([ 5305,     1,    13, 27453,  5116, 28895,  5562,    47,  5036,   733,
          263,  3911,   392, 21542,   270, 25833,   306,  1544, 34869,   372])
['real', '"', '.', 'Mir', 'kin', 'thought', 'that', 'P', 'fe', 'iff', 'er', 'part', 'and', 'played', 'it', 'perfect', 'ly', 'He', 'described', 'her']
tensor([   13,  2215,    33,   433, 11873, 38631,  1640, 10215,  8243,   282,
         8738,  6749, 16354, 29818, 26405,  9452,  1694, 44140, 18108,    64])
['.', 'When', 'B', 'art', 'being', 'fitted', 'for', 'cor', 'rection', 'al', 'opt', 'ician', 'former', 'Israeli', 'Prime', 'Min', 'ister', 'Begin', 'had', 'a']
New Epoch 56
2021-09-13 10:56:43.967 |     SUCCESS      | R

2021-09-13 10:56:55.574 |     SUCCESS      | Loaded folder:      QmXwfPoh2QFYqC6cYcW8kzyd9ruFfhnUi2kVBkdhawjUzj
2021-09-13 10:56:57.696 |     SUCCESS      | Loaded folder:      QmRjFNn3XpYMycVzTE4YcVcxk45vNZcTAjKmtEqPLKwAWd
2021-09-13 10:56:58.350 |     SUCCESS      | Downloaded:         Wikitext_Æthelwulf.txt
2021-09-13 10:56:58.351 |     SUCCESS      | Saved:              Wikitext_Æthelwulf.txt
tensor([ 5562, 16885, 12501,   320,   602,   448,    11, 16670,  1169, 12227,
          505, 11261,  1662, 14150, 47436,   785, 16838,  1462, 10365,  3507])
['that', 'both', 'dec', 'im', 'ations', 'out', ',', 'although', 'the', 'second', 'one', 'may', 'not', 'have', 'been', 'com', 'pleted', 'to', 'opp', 'osition']
tensor([ 4826,  1424,  1169, 24419, 11720,    79,  2703,  1014,  1640,  5746,
          126,   228, 37274,    86,  4754, 18302,   594,    32,  1652,   445])
['Ab', 'els', 'the', 'emb', 'assy', 'p', 'aving', 'way', 'for', 'Ã', '�', '�', 'thel', 'w', 'ulf', 'pres', 'ence', 'A', 'lf', '

KeyboardInterrupt: 

In [38]:
from transformers import AutoModel

model = AutoModel.from_pretrained("bert-base-cased")


Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
